# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW-oVIr4RtKrnMcO1INFWyplF66Hsa2b
"""

# !pip install opencv-python-headless
# !pip install opencv-python
# !pip install ultralytics
# !pip install pygame


import cv2
from ultralytics import YOLO
import time
import pygame
import threading
import streamlit as st
import numpy as np


# AudioPlayer class remains unchanged
class AudioPlayer:
    def __init__(self, audio_files):
        pygame.mixer.init()
        self.audio_files = audio_files
        self.current_audio_index = 0

    def play_next_audio(self):
        pygame.mixer.music.load(self.audio_files[self.current_audio_index])
        pygame.mixer.music.play()
        self.current_audio_index = (self.current_audio_index + 1) % len(self.audio_files)

    def async_play_audio(self):
        if not pygame.mixer.music.get_busy():
            threading.Thread(target=self.play_next_audio).start()


class DrowsinessDetector:
    def __init__(self, model_path, audio_player, drowsiness_duration=2):
        self.model = YOLO(model_path)
        self.audio_player = audio_player
        self.drowsy_start_time = None
        self.drowsiness_duration = drowsiness_duration

    def process_frame(self, frame):
        resized_frame = cv2.resize(frame, (320, 240))
        results = self.model(resized_frame)
        annotated_frame = results[0].plot()
        drowsy_detected = False

        if results[0].boxes:
            for box in results[0].boxes:
                if box.cls == 1:  # Assuming 'drowsy' is class 1
                    drowsy_detected = True
                    if self.drowsy_start_time is None:
                        self.drowsy_start_time = time.time()
                    elif time.time() - self.drowsy_start_time >= self.drowsiness_duration:
                        self.audio_player.async_play_audio()
                else:
                    self.drowsy_start_time = None
        else:
            self.drowsy_start_time = None

        return annotated_frame, drowsy_detected


def main():
    st.markdown("""
        <style>
        .centered-alert {
            position: fixed;
            top: 30%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 9999;
            background: #ffcccc;
            border: 3px solid #ff0000;
            border-radius: 16px;
            padding: 40px 60px;
            font-size: 2rem;
            font-weight: bold;
            color: #b30000;
            text-align: center;
            box-shadow: 0 0 20px #ff0000;
        }
        </style>
    """, unsafe_allow_html=True)

    st.title(" Drowsiness Detection System")
    st.write("""
        This app uses YOLOv8 to detect drowsiness in real-time from your webcam or uploaded video. If drowsiness is detected, an alert will pop up and an audio warning will play.
    """)

    st.sidebar.header("Configuration")
    model_path = st.sidebar.text_input("Model Path", "best.pt")
    drowsiness_duration = st.sidebar.slider("Drowsiness Duration (seconds)", 1, 10, 2)
    st.sidebar.write("Select input source:")
    uploaded_file = st.sidebar.file_uploader("Video file", type=["mp4", "avi", "mov"])
    use_webcam = st.sidebar.checkbox("Use Webcam", value=True)

    audio_files = [f"audio files/{f}" for f in ["a.mp3", "b.mp3", "c.mp3", "d.mp3", "e.mp3"]]
    audio_player = AudioPlayer(audio_files)
    drowsiness_detector = DrowsinessDetector(model_path, audio_player, drowsiness_duration)

    if uploaded_file is not None:
        st.video(uploaded_file)
        temp_video_path = f"temp_video.mp4"
        with open(temp_video_path, "wb") as f:
            f.write(uploaded_file.read())
        cap = cv2.VideoCapture(temp_video_path)
    elif use_webcam:
        cap = cv2.VideoCapture(0)
    else:
        st.info("Please upload a video or select webcam.")
        return

    stframe = st.empty()
    alert_placeholder = st.empty()
    while cap.isOpened():
        success, frame = cap.read()
        if not success:
            break
        annotated_frame, drowsy_detected = drowsiness_detector.process_frame(frame)
        annotated_frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)
        stframe.image(annotated_frame_rgb, channels="RGB", caption="Live Detection", use_column_width=True)
        if drowsy_detected:
            alert_placeholder.markdown(
                '<div class="centered-alert">⚠️ Drowsiness Detected!</div>', unsafe_allow_html=True
            )
        else:
            alert_placeholder.empty()
        time.sleep(0.03)

    cap.release()
    pygame.mixer.quit()

if __name__ == "__main__":
    main()